#!/usr/bin/env bash
readonly NAME=_proxy
readonly ROOT=$(dirname $0)/$NAME

config=${1:-shadowsocks}

pushd $ROOT > /dev/null

nohup ss-local -c conf/${config}.json > log/error.log 2>&1 &

popd > /dev/null
